[package]
name = "tracing-datadog"
version = "0.6.2"
edition = "2024"
description = "tracing subscriber for DataDog"
categories = ["development-tools::debugging", "development-tools::profiling"]
repository = "https://github.com/sulami/tracing-datadog"
license = "MIT"

[features]
default = []
ahash = ["dep:ahash"]
http = ["dep:http"]

[dependencies]
ahash = { version = "0.8", optional = true, features = ["serde"] }
http = { version = "1", optional = true }
jiff = { version = "0.2", features = ["serde"] }
rand = "0.10"
reqwest = { version = "0.13", default-features = false, features = ["blocking"] }
rmp-serde = "1"
serde = "1"
serde_json = "1"
tracing = { version = "0.1", default-features = false }
tracing-core = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = ["std"] }

[dev-dependencies]
tracing-subscriber = { version = "0.3", default-features = false, features = ["std", "registry"] }

[package.metadata.docs.rs]
features = ["http"]
