[package]
name = "tracing-datadog"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }

[dev-dependencies]
tracing-subscriber = { version = "0.3", default-features = false, features = ["std", "registry"] }
